# Generated by Django 4.1.4 on 2022-12-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Men',
        ),
    ]
